services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - devcontainer.env
      - devcontainer-private.env
    command: sleep infinity

  qdrant:
    image: qdrant/qdrant:v1.14.0
    ports:
      - 6333:6333
    volumes:
      - qdrant-storage:/qdrant/storage
      
volumes:
  qdrant-storage:  